package stridealign

func BLOSUM30() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum30") }
func BLOSUM35() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum35") }
func BLOSUM40() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum40") }
func BLOSUM45() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum45") }
func BLOSUM50() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum50") }
func BLOSUM55() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum55") }
func BLOSUM60() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum60") }
func BLOSUM62() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum62") }
func BLOSUM65() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum65") }
func BLOSUM70() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum70") }
func BLOSUM75() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum75") }
func BLOSUM80() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum80") }
func BLOSUM85() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum85") }
func BLOSUM90() (*SubstitutionMatrix, error)  { return BuiltinMatrix("blosum90") }
func BLOSUM100() (*SubstitutionMatrix, error) { return BuiltinMatrix("blosum100") }

func PAM10() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam10") }
func PAM20() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam20") }
func PAM30() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam30") }
func PAM40() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam40") }
func PAM50() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam50") }
func PAM60() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam60") }
func PAM70() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam70") }
func PAM80() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam80") }
func PAM90() (*SubstitutionMatrix, error)  { return BuiltinMatrix("pam90") }
func PAM100() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam100") }
func PAM110() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam110") }
func PAM120() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam120") }
func PAM130() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam130") }
func PAM140() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam140") }
func PAM150() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam150") }
func PAM160() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam160") }
func PAM170() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam170") }
func PAM180() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam180") }
func PAM190() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam190") }
func PAM200() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam200") }
func PAM210() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam210") }
func PAM220() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam220") }
func PAM230() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam230") }
func PAM240() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam240") }
func PAM250() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam250") }
func PAM260() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam260") }
func PAM270() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam270") }
func PAM280() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam280") }
func PAM290() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam290") }
func PAM300() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam300") }
func PAM310() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam310") }
func PAM320() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam320") }
func PAM330() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam330") }
func PAM340() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam340") }
func PAM350() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam350") }
func PAM360() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam360") }
func PAM370() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam370") }
func PAM380() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam380") }
func PAM390() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam390") }
func PAM400() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam400") }
func PAM410() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam410") }
func PAM420() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam420") }
func PAM430() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam430") }
func PAM440() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam440") }
func PAM450() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam450") }
func PAM460() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam460") }
func PAM470() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam470") }
func PAM480() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam480") }
func PAM490() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam490") }
func PAM500() (*SubstitutionMatrix, error) { return BuiltinMatrix("pam500") }

func NUC44() (*SubstitutionMatrix, error)     { return BuiltinMatrix("nuc44") }
func DNAMatch() (*SubstitutionMatrix, error)  { return BuiltinMatrix("dna_match") }
func ASCIIText() (*SubstitutionMatrix, error) { return BuiltinMatrix("ascii_text") }
