#!/usr/bin/env python3
"""Generate the PostgreSQL 16–18 extension SQL surface.

The repetitive wrappers are generated so scorer aliases, one-to-many forms,
and ranking forms cannot drift apart. The generated file is committed because
PostgreSQL package managers expect the versioned SQL file in source archives.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "stride_align--0.6.0.sql"


def create_c(name: str, args: str, result: str, symbol: str) -> str:
    return f"""CREATE FUNCTION {name}({args}) RETURNS {result}
AS 'MODULE_PATHNAME', '{symbol}'
LANGUAGE C IMMUTABLE PARALLEL SAFE;
"""


def create_sql(
    name: str,
    args: str,
    result: str,
    expression: str,
    *,
    strict: bool = True,
) -> str:
    null_policy = " STRICT" if strict else ""
    return f"""CREATE FUNCTION {name}({args}) RETURNS {result}
LANGUAGE SQL IMMUTABLE PARALLEL SAFE{null_policy}
RETURN {expression};
"""


OPTIONS = "2, -1, -1, -1, 0.1, 0.7, 4"
ALIGNMENT_OPTION_NAMES = (
    "match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4"
)


def score(
    scorer: str,
    *,
    query: str = "query",
    target: str = "target",
    options: str = OPTIONS,
    similarity_cutoff: str = "NULL",
    distance_cutoff: str = "NULL",
) -> str:
    return (
        f"_stride_score_native({query}, {target}, '{scorer}', {options}, "
        f"{similarity_cutoff}, {distance_cutoff})"
    )


def scores(
    scorer: str,
    *,
    options: str = OPTIONS,
    similarity_cutoff: str = "NULL",
    distance_cutoff: str = "NULL",
) -> str:
    return (
        f"_stride_scores_native(query, targets, '{scorer}', {options}, "
        f"{similarity_cutoff}, {distance_cutoff})"
    )


def top_k(
    scorer: str,
    *,
    best: bool = False,
    options: str = OPTIONS,
) -> str:
    return (
        f"_stride_top_k_native(query, targets, '{scorer}', "
        f"{'1' if best else 'k'}, {'true' if best else 'false'}, {options})"
    )


def main() -> None:
    sql: list[str] = [
        "-- Generated by bindings/postgres/generate_sql.py.\n",
        "-- stride-align 0.6.0 for PostgreSQL 16, 17, and 18.\n",
        create_c(
            "_stride_score_native",
            "query text, target text, scorer text, match_score bigint, "
            "mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, "
            "prefix_weight double precision, prefix_threshold double precision, "
            "prefix_cap bigint, similarity_cutoff double precision, distance_cutoff bigint",
            "double precision",
            "stride_pg_score",
        ),
        create_c(
            "_stride_scores_native",
            "query text, targets text[], scorer text, match_score bigint, "
            "mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, "
            "prefix_weight double precision, prefix_threshold double precision, "
            "prefix_cap bigint, similarity_cutoff double precision, distance_cutoff bigint",
            "double precision[]",
            "stride_pg_scores",
        ),
        create_c(
            "_stride_top_k_native",
            "query text, targets text[], scorer text, k bigint, best boolean, "
            "match_score bigint, mismatch_score bigint, gap_open_score bigint, "
            "gap_extend_score bigint, prefix_weight double precision, "
            "prefix_threshold double precision, prefix_cap bigint",
            "jsonb",
            "stride_pg_top_k",
        ),
        create_c(
            "_stride_cdist_native",
            "queries text[], targets text[], scorer text, match_score bigint, "
            "mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, "
            "prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint",
            "double precision[]",
            "stride_pg_cdist",
        ),
        create_c(
            "_stride_cdist_above_threshold_native",
            "queries text[], targets text[], scorer text, threshold double precision, "
            "match_score bigint, mismatch_score bigint, gap_open_score bigint, "
            "gap_extend_score bigint, prefix_weight double precision, "
            "prefix_threshold double precision, prefix_cap bigint",
            "jsonb",
            "stride_pg_cdist_above_threshold",
        ),
        create_c(
            "_stride_cdist_top_k_native",
            "queries text[], targets text[], scorer text, k bigint, reject_duplicates boolean, "
            "match_score bigint, mismatch_score bigint, gap_open_score bigint, "
            "gap_extend_score bigint, prefix_weight double precision, "
            "prefix_threshold double precision, prefix_cap bigint",
            "jsonb",
            "stride_pg_cdist_top_k",
        ),
        create_c(
            "_stride_cdist_top_k_per_query_native",
            "queries text[], targets text[], scorer text, k bigint, "
            "match_score bigint, mismatch_score bigint, gap_open_score bigint, "
            "gap_extend_score bigint, prefix_weight double precision, "
            "prefix_threshold double precision, prefix_cap bigint",
            "jsonb",
            "stride_pg_cdist_top_k_per_query",
        ),
    ]

    # Package and database-encoding diagnostics.
    sql.extend(
        [
            create_c("stride_detect_best_backend", "", "text", "stride_pg_backend"),
            create_c("stride_align_simd_level", "", "text", "stride_pg_backend"),
            create_c("_stride_encoding_info", "", "jsonb", "stride_pg_encoding"),
            create_c(
                "_stride_prepare_info",
                "query text, target text",
                "jsonb",
                "stride_pg_prepare_info",
            ),
            create_sql(
                "stride_available_backends",
                "",
                "text[]",
                "ARRAY[stride_detect_best_backend()]",
            ),
            create_sql(
                "stride_backend_is_available",
                "backend text",
                "boolean",
                "lower(backend) = lower(stride_detect_best_backend())",
            ),
        ]
    )

    # Pairwise integer distances and normalized similarities.
    integer_pairs = (
        ("levenshtein", "stride_levenshtein", "stride_levenshtein_similarity"),
        ("damerau_levenshtein", "stride_osa", "stride_osa_similarity"),
        (
            "true_damerau_levenshtein",
            "stride_true_damerau_levenshtein",
            "stride_true_damerau_levenshtein_similarity",
        ),
        ("indel", "stride_indel", "stride_indel_similarity"),
        ("hamming", "stride_hamming", "stride_hamming_similarity"),
    )
    for scorer_name, raw_name, similarity_name in integer_pairs:
        normalized = scorer_name + "_normalized"
        sql.append(
            create_sql(
                raw_name,
                "query text, target text",
                "bigint",
                score(scorer_name) + "::bigint",
            )
        )
        sql.append(
            create_sql(
                similarity_name,
                "query text, target text",
                "double precision",
                score(normalized),
            )
        )

    # Python-style score aliases and their cutoff overloads.
    score_families = (
        ("levenshtein", "levenshtein", True),
        ("levenshtein_normalized", "levenshtein_normalized", False),
        ("damerau_levenshtein", "damerau_levenshtein", True),
        ("damerau_levenshtein_normalized", "damerau_levenshtein_normalized", False),
        ("true_damerau_levenshtein", "true_damerau_levenshtein", True),
        (
            "true_damerau_levenshtein_normalized",
            "true_damerau_levenshtein_normalized",
            False,
        ),
        ("indel", "indel", True),
        ("indel_normalized", "indel_normalized", False),
        ("hamming", "hamming", True),
        ("hamming_normalized", "hamming_normalized", False),
    )
    for stem, scorer_name, integral in score_families:
        result = "bigint" if integral else "double precision"
        expression = score(scorer_name) + ("::bigint" if integral else "")
        sql.append(
            create_sql(f"stride_{stem}_score", "query text, target text", result, expression)
        )
        if stem in {"levenshtein", "indel"}:
            sql.append(
                create_sql(
                    f"stride_{stem}_score",
                    "query text, target text, score_cutoff bigint",
                    result,
                    score(scorer_name, distance_cutoff="score_cutoff") + "::bigint",
                )
            )
        elif stem in {"levenshtein_normalized", "indel_normalized"}:
            sql.append(
                create_sql(
                    f"stride_{stem}_score",
                    "query text, target text, score_cutoff double precision",
                    result,
                    score(scorer_name, similarity_cutoff="score_cutoff"),
                )
            )

    sql.extend(
        [
            create_sql("stride_jaro", "query text, target text", "double precision", score("jaro")),
            create_sql(
                "stride_jaro_similarity",
                "query text, target text",
                "double precision",
                score("jaro"),
            ),
            create_sql(
                "stride_jaro_winkler",
                "query text, target text",
                "double precision",
                score("jaro_winkler"),
            ),
            create_sql(
                "stride_jaro_winkler_similarity",
                "query text, target text, prefix_weight double precision DEFAULT 0.1, "
                "prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4",
                "double precision",
                score(
                    "jaro_winkler",
                    options="2, -1, -1, -1, prefix_weight, prefix_threshold, prefix_cap",
                ),
            ),
        ]
    )

    # Linear and affine alignment names, including the Farrar aliases.
    for local, stem in ((True, "smith_waterman"), (False, "needleman_wunsch")):
        scorer_name = stem
        normalized = stem + "_normalized"
        for name in (f"stride_{stem}", f"stride_{stem}_score"):
            sql.append(
                create_sql(
                    name,
                    "query text, target text, match_score bigint DEFAULT 2, "
                    "mismatch_score bigint DEFAULT -1, gap_score bigint DEFAULT -1",
                    "bigint",
                    score(
                        scorer_name,
                        options="match_score, mismatch_score, gap_score, gap_score, 0.1, 0.7, 4",
                    )
                    + "::bigint",
                )
            )
        sql.append(
            create_sql(
                f"stride_{stem}_affine",
                "query text, target text, match_score bigint DEFAULT 2, "
                "mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -2, "
                "gap_extend_score bigint DEFAULT -1",
                "bigint",
                score(
                    scorer_name,
                    options=ALIGNMENT_OPTION_NAMES,
                )
                + "::bigint",
            )
        )
        sql.append(
            create_sql(
                f"stride_{stem}_normalized_score",
                "query text, target text, match_score bigint DEFAULT 2, "
                "mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, "
                "gap_extend_score bigint DEFAULT -1",
                "double precision",
                score(
                    normalized,
                    options=ALIGNMENT_OPTION_NAMES,
                ),
            )
        )
        if local:
            sql.append(
                create_sql(
                    "stride_smith_waterman_farrar_score",
                    "query text, target text, match_score bigint DEFAULT 2, "
                    "mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, "
                    "gap_extend_score bigint DEFAULT -1",
                    "bigint",
                    score(
                        scorer_name,
                        options=ALIGNMENT_OPTION_NAMES,
                    )
                    + "::bigint",
                )
            )
            sql.append(
                create_sql(
                    "stride_smith_waterman_farrar_normalized_score",
                    "query text, target text, match_score bigint DEFAULT 2, "
                    "mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, "
                    "gap_extend_score bigint DEFAULT -1",
                    "double precision",
                    score(
                        normalized,
                        options=ALIGNMENT_OPTION_NAMES,
                    ),
                )
            )

    # One-to-many scorers.
    plural_families = (
        ("levenshtein_scores", "levenshtein", True),
        ("levenshtein_normalized_scores", "levenshtein_normalized", False),
        ("damerau_levenshtein_scores", "damerau_levenshtein", True),
        ("damerau_levenshtein_normalized_scores", "damerau_levenshtein_normalized", False),
        ("true_damerau_levenshtein_scores", "true_damerau_levenshtein", True),
        (
            "true_damerau_levenshtein_normalized_scores",
            "true_damerau_levenshtein_normalized",
            False,
        ),
        ("indel_scores", "indel", True),
        ("indel_normalized_scores", "indel_normalized", False),
        ("hamming_scores", "hamming", True),
        ("hamming_normalized_scores", "hamming_normalized", False),
        ("jaro_similarities", "jaro", False),
        ("jaro_winkler_similarities", "jaro_winkler", False),
        ("smith_waterman_scores", "smith_waterman", True),
        ("smith_waterman_normalized_scores", "smith_waterman_normalized", False),
        ("smith_waterman_farrar_scores", "smith_waterman", True),
        ("smith_waterman_farrar_normalized_scores", "smith_waterman_normalized", False),
        ("needleman_wunsch_scores", "needleman_wunsch", True),
        ("needleman_wunsch_normalized_scores", "needleman_wunsch_normalized", False),
    )
    for name, scorer_name, integral in plural_families:
        result = "bigint[]" if integral else "double precision[]"
        expression = scores(scorer_name) + ("::bigint[]" if integral else "")
        sql.append(create_sql(f"stride_{name}", "query text, targets text[]", result, expression))

    sql.append(
        create_sql(
            "stride_scores",
            "query text, targets text[], scorer text",
            "double precision[]",
            f"_stride_scores_native(query, targets, scorer, {OPTIONS}, NULL, NULL)",
        )
    )

    # Bounded rankings. All retain native C++ length bounds and heap cutoffs.
    rank_families = (
        ("levenshtein", "levenshtein"),
        ("levenshtein_normalized", "levenshtein_normalized"),
        ("damerau_levenshtein", "damerau_levenshtein"),
        ("damerau_levenshtein_normalized", "damerau_levenshtein_normalized"),
        ("true_damerau_levenshtein", "true_damerau_levenshtein"),
        ("true_damerau_levenshtein_normalized", "true_damerau_levenshtein_normalized"),
        ("indel", "indel"),
        ("indel_normalized", "indel_normalized"),
        ("hamming", "hamming"),
        ("hamming_normalized", "hamming_normalized"),
        ("jaro", "jaro"),
        ("jaro_winkler", "jaro_winkler"),
        ("smith_waterman", "smith_waterman"),
    )
    for stem, scorer_name in rank_families:
        sql.append(
            create_sql(
                f"stride_{stem}_top_k",
                "query text, targets text[], k bigint DEFAULT 5",
                "jsonb",
                top_k(scorer_name),
            )
        )
        sql.append(
            create_sql(
                f"stride_{stem}_best",
                "query text, targets text[]",
                "jsonb",
                top_k(scorer_name, best=True),
            )
        )
    sql.extend(
        [
            create_sql(
                "stride_extract",
                "query text, targets text[], scorer text, k bigint DEFAULT 5",
                "jsonb",
                f"_stride_top_k_native(query, targets, scorer, k, false, {OPTIONS})",
            ),
            create_sql(
                "stride_extract_best",
                "query text, targets text[], scorer text",
                "jsonb",
                f"_stride_top_k_native(query, targets, scorer, 1, true, {OPTIONS})",
            ),
        ]
    )

    common_options = (
        "match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, "
        "gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1, "
        "prefix_weight double precision DEFAULT 0.1, "
        "prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4"
    )
    option_names = (
        "match_score, mismatch_score, gap_open_score, gap_extend_score, "
        "prefix_weight, prefix_threshold, prefix_cap"
    )
    sql.extend(
        [
            create_sql(
                "stride_cdist",
                f"queries text[], targets text[], scorer text, {common_options}",
                "double precision[]",
                f"_stride_cdist_native(queries, targets, scorer, {option_names})",
            ),
            create_sql(
                "stride_cdist_above_threshold",
                "queries text[], targets text[], scorer text, "
                f"threshold double precision, {common_options}",
                "jsonb",
                "_stride_cdist_above_threshold_native(queries, targets, "
                f"scorer, threshold, {option_names})",
            ),
            create_sql(
                "stride_cdist_top_k",
                "queries text[], targets text[], scorer text, k bigint, "
                f"reject_duplicates boolean DEFAULT false, {common_options}",
                "jsonb",
                "_stride_cdist_top_k_native(queries, targets, scorer, k, "
                f"reject_duplicates, {option_names})",
            ),
            create_sql(
                "stride_cdist_top_k_per_query",
                "queries text[], targets text[], scorer text, "
                f"k bigint DEFAULT 5, {common_options}",
                "jsonb",
                "_stride_cdist_top_k_per_query_native(queries, targets, "
                f"scorer, k, {option_names})",
            ),
        ]
    )

    # LCS, n-grams, and token similarities.
    sql.extend(
        [
            create_c(
                "stride_lcs_length", "query text, target text", "bigint", "stride_pg_lcs_length"
            ),
            create_c(
                "stride_lcs_substring_length",
                "query text, target text",
                "bigint",
                "stride_pg_lcs_substring_length",
            ),
            create_c(
                "stride_lcs_substring", "query text, target text", "text", "stride_pg_lcs_substring"
            ),
            create_c(
                "_stride_ngram_native",
                "query text, target text, metric text, n bigint",
                "double precision",
                "stride_pg_ngram",
            ),
            create_c(
                "_stride_ngram_scores_native",
                "query text, targets text[], metric text, n bigint",
                "double precision[]",
                "stride_pg_ngram_scores",
            ),
            create_c(
                "_stride_similarity_native",
                "query text, target text, metric text",
                "double precision",
                "stride_pg_similarity",
            ),
            create_c(
                "_stride_similarity_scores_native",
                "query text, targets text[], metric text",
                "double precision[]",
                "stride_pg_similarity_scores",
            ),
        ]
    )
    for metric in ("jaccard", "dice", "cosine", "overlap"):
        sql.append(
            create_sql(
                f"stride_{metric}",
                "query text, target text, n bigint DEFAULT 2",
                "double precision",
                f"_stride_ngram_native(query, target, '{metric}', n)",
            )
        )
        sql.append(
            create_sql(
                f"stride_{metric}_similarities",
                "query text, targets text[], n bigint DEFAULT 2",
                "double precision[]",
                f"_stride_ngram_scores_native(query, targets, '{metric}', n)",
            )
        )
    similarity_names = (
        ("ratcliff_obershelp_similarity", "ratcliff_obershelp"),
        ("partial_ratio", "partial_ratio"),
        ("token_sort_ratio", "token_sort_ratio"),
        ("token_set_ratio", "token_set_ratio"),
        ("partial_token_sort_ratio", "partial_token_sort_ratio"),
        ("partial_token_set_ratio", "partial_token_set_ratio"),
        ("wratio", "wratio"),
    )
    for singular, metric in similarity_names:
        plural = (
            "ratcliff_obershelp_similarities"
            if singular == "ratcliff_obershelp_similarity"
            else singular.removesuffix("ratio") + "ratios"
            if singular.endswith("ratio")
            else "wratios"
        )
        sql.append(
            create_sql(
                f"stride_{singular}",
                "query text, target text",
                "double precision",
                f"_stride_similarity_native(query, target, '{metric}')",
            )
        )
        sql.append(
            create_sql(
                f"stride_{plural}",
                "query text, targets text[]",
                "double precision[]",
                f"_stride_similarity_scores_native(query, targets, '{metric}')",
            )
        )
    sql.extend(
        [
            create_c(
                "stride_monge_elkan",
                "query text, target text, inner_scorer text DEFAULT 'jaro', "
                '"symmetric" boolean DEFAULT false',
                "double precision",
                "stride_pg_monge_elkan",
            ),
            create_c(
                "_stride_phonetic_native",
                "algorithm text, input text, first_option bigint, "
                "first_flag boolean, second_flag boolean",
                "text",
                "stride_pg_phonetic",
            ),
            create_c(
                "_stride_phonetic_equal_native",
                "algorithm text, query text, target text, first_option bigint",
                "boolean",
                "stride_pg_phonetic_equal",
            ),
        ]
    )

    for public, algorithm in (
        ("soundex", "soundex"),
        ("nysiis", "nysiis"),
        ("match_rating_codex", "match_rating_codex"),
        ("caverphone", "caverphone"),
        ("cologne_phonetic", "cologne_phonetic"),
    ):
        sql.append(
            create_sql(
                f"stride_{public}",
                "input text",
                "text",
                f"_stride_phonetic_native('{algorithm}', input, 0, true, true)",
            )
        )
    for public, algorithm in (
        ("soundex_equal", "soundex"),
        ("nysiis_equal", "nysiis"),
        ("match_rating_compare", "match_rating_compare"),
    ):
        sql.append(
            create_sql(
                f"stride_{public}",
                "query text, target text",
                "boolean",
                f"_stride_phonetic_equal_native('{algorithm}', query, target, 0)",
            )
        )
    sql.extend(
        [
            create_sql(
                "stride_metaphone",
                "input text, variant bigint DEFAULT 0",
                "text",
                "_stride_phonetic_native('metaphone', input, variant, true, true)",
            ),
            create_sql(
                "stride_metaphone_equal",
                "query text, target text, variant bigint DEFAULT 0",
                "boolean",
                "_stride_phonetic_equal_native('metaphone', query, target, variant)",
            ),
            create_sql(
                "stride_daitch_mokotoff",
                "input text, branching boolean DEFAULT true, folding boolean DEFAULT true",
                "text",
                "_stride_phonetic_native('daitch_mokotoff', input, 0, branching, folding)",
            ),
            create_c(
                "stride_double_metaphone",
                "input text, max_length bigint DEFAULT 64, variant bigint DEFAULT 0",
                "jsonb",
                "stride_pg_double_metaphone",
            ),
            create_c(
                "stride_beider_morse",
                "input text, rule_type bigint DEFAULT 0, concatenate boolean DEFAULT true, "
                "max_phonemes bigint DEFAULT 20",
                "text",
                "stride_pg_beider_morse",
            ),
        ]
    )

    # Numeric sequence alignment.
    sql.extend(
        [
            create_c(
                "_stride_dtw_native",
                'query anyarray, target anyarray, "window" double precision, '
                "distance text, score_cutoff double precision",
                "double precision",
                "stride_pg_dtw",
            ),
            create_c(
                "_stride_dtw_distances_native",
                'query anyarray, targets anyarray, "window" double precision, '
                "distance text, score_cutoff double precision",
                "double precision[]",
                "stride_pg_dtw_distances",
            ),
        ]
    )
    for array_type, default_distance in (
        ("double precision[]", "l2_squared"),
        ("smallint[]", "l1"),
    ):
        nested = array_type
        sql.append(
            create_sql(
                "stride_dtw",
                f'query {array_type}, target {array_type}, "window" double precision DEFAULT NULL, '
                f"distance text DEFAULT '{default_distance}', "
                "score_cutoff double precision DEFAULT NULL",
                "double precision",
                '_stride_dtw_native(query, target, "window", distance, score_cutoff)',
                strict=False,
            )
        )
        sql.append(
            create_sql(
                "stride_dtw_distances",
                f'query {array_type}, targets {nested}, "window" double precision DEFAULT NULL, '
                f"distance text DEFAULT '{default_distance}', "
                "score_cutoff double precision DEFAULT NULL",
                "double precision[]",
                '_stride_dtw_distances_native(query, targets, "window", distance, score_cutoff)',
                strict=False,
            )
        )

    # Traceback and CIGAR families return JSONB, preserving strings in the
    # database's native server encoding.
    sql.append(
        create_c(
            "_stride_alignment_path_native",
            "query text, target text, local boolean, match_score bigint, "
            "mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint",
            "jsonb",
            "stride_pg_alignment_path",
        )
    )
    for local, stem in ((True, "smith_waterman"), (False, "needleman_wunsch")):
        call = (
            f"_stride_alignment_path_native(query, target, {'true' if local else 'false'}, "
            "match_score, mismatch_score, gap_open_score, gap_extend_score)"
        )
        args = (
            "query text, target text, match_score bigint DEFAULT 2, "
            "mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, "
            "gap_extend_score bigint DEFAULT -1"
        )
        for suffix in ("path", "path_info"):
            sql.append(create_sql(f"stride_{stem}_{suffix}", args, "jsonb", call))
        for suffix in ("cigar", "trace_cigar", "trade_cigar"):
            sql.append(
                create_sql(
                    f"stride_{stem}_{suffix}",
                    args,
                    "text",
                    f"({call})->>'cigar'",
                )
            )

    # Substitution matrices are opaque BYTEA values in PostgreSQL. Built-in
    # catalog names remain TEXT, and every consumer is overloaded for both.
    sql.extend(
        [
            create_c(
                "stride_matrix_available",
                "",
                "text[]",
                "stride_pg_matrix_available",
            ),
            create_c(
                "stride_keyboard_available",
                "",
                "text[]",
                "stride_pg_keyboard_available",
            ),
            create_c(
                "stride_identity_matrix",
                "alphabet text, match_score bigint DEFAULT 1, mismatch_score bigint DEFAULT 0, "
                "wildcard text DEFAULT '*', name text DEFAULT 'IDENTITY', "
                "gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, "
                "gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_identity_matrix",
            ),
            create_c(
                "stride_ascii_matrix",
                "match_score bigint DEFAULT 1, mismatch_score bigint DEFAULT -1, "
                "name text DEFAULT 'ASCII', gap_score bigint DEFAULT -1, "
                "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_ascii_matrix",
            ),
            create_c(
                "stride_matrix_from_ncbi_text",
                "matrix_text text, name text DEFAULT '<unnamed>', gap_score bigint DEFAULT -4, "
                "wildcard text DEFAULT 'X', gap_open bigint DEFAULT NULL, "
                "gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_matrix_from_ncbi_text",
            ),
        ]
    )

    for grid_type in ("smallint[]", "integer[]", "bigint[]"):
        sql.append(
            create_c(
                "stride_substitution_matrix",
                f"name text, alphabet text, scores {grid_type}, "
                "gap_score bigint DEFAULT -4, wildcard text DEFAULT 'X', "
                "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_substitution_matrix",
            )
        )

    sql.extend(
        [
            create_c(
                "stride_keyboard_from_confusion_counts",
                "counts double precision[], alphabet text DEFAULT NULL, "
                "name text DEFAULT 'KEYBOARD', scale double precision DEFAULT 2.0, "
                "match_margin bigint DEFAULT 4, floor double precision DEFAULT NULL, "
                "wildcard text DEFAULT NULL, gap_score bigint DEFAULT -1, "
                "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_keyboard_from_confusion_counts",
            ),
            create_c(
                "stride_keyboard_from_npy",
                "contents bytea, name text DEFAULT 'KEYBOARD', alphabet text DEFAULT NULL, "
                "wildcard text DEFAULT NULL, transpose boolean DEFAULT false, "
                "gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, "
                "gap_extend bigint DEFAULT NULL",
                "bytea",
                "stride_pg_keyboard_from_npy",
            ),
        ]
    )

    matrix_types = ("text", "bytea")
    for matrix_type in matrix_types:
        sql.extend(
            [
                create_c(
                    "stride_matrix_info",
                    f"matrix_value {matrix_type}",
                    "jsonb",
                    "stride_pg_matrix_info",
                ),
                create_c(
                    "stride_matrix_encode",
                    f"matrix_value {matrix_type}, input text",
                    "smallint[]",
                    "stride_pg_matrix_encode",
                ),
                create_c(
                    "stride_matrix_score_step_limit",
                    f"matrix_value {matrix_type}, gap_open bigint DEFAULT NULL, "
                    "gap_extend bigint DEFAULT NULL",
                    "bigint",
                    "stride_pg_matrix_score_step_limit",
                ),
                create_c(
                    "stride_matrix_transpose",
                    f"matrix_value {matrix_type}, name text DEFAULT NULL",
                    "bytea",
                    "stride_pg_matrix_transpose",
                ),
                create_c(
                    "stride_substitution_matrix_score",
                    f"matrix_value {matrix_type}, query text, target text",
                    "bigint",
                    "stride_pg_substitution_matrix_score",
                ),
            ]
        )

        for result, native_name in (
            ("bigint", "_stride_matrix_alignment_score_native"),
            ("jsonb", "_stride_matrix_alignment_path_native"),
            ("text", "_stride_matrix_alignment_cigar_native"),
        ):
            sql.append(
                create_c(
                    native_name,
                    f"query text, target text, matrix_value {matrix_type}, local boolean, "
                    "return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint",
                    result,
                    "stride_pg_matrix_alignment",
                )
            )
        sql.extend(
            [
                create_c(
                    "_stride_matrix_scores_native",
                    f"query text, targets text[], matrix_value {matrix_type}, local boolean, "
                    "gap_open bigint, gap_extend bigint",
                    "bigint[]",
                    "stride_pg_matrix_scores",
                ),
                create_c(
                    "_stride_matrix_cdist_native",
                    f"queries text[], targets text[], matrix_value {matrix_type}, local boolean, "
                    "gap_open bigint, gap_extend bigint",
                    "bigint[]",
                    "stride_pg_matrix_cdist",
                ),
                create_c(
                    "_stride_matrix_rank_native",
                    f"queries text[], targets text[], matrix_value {matrix_type}, local boolean, "
                    "parameter bigint, top_k boolean, gap_open bigint, gap_extend bigint",
                    "jsonb",
                    "stride_pg_matrix_rank",
                ),
            ]
        )

        for local, stem in ((True, "smith_waterman"), (False, "needleman_wunsch")):
            flag = "true" if local else "false"
            scalar_args = (
                f"query text, target text, matrix_value {matrix_type}, "
                "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL"
            )
            score_call = (
                f"_stride_matrix_alignment_score_native(query, target, matrix_value, {flag}, "
                "false, false, gap_open, gap_extend)"
            )
            sql.append(
                create_sql(
                    f"stride_{stem}_matrix_score",
                    scalar_args,
                    "bigint",
                    score_call,
                    strict=False,
                )
            )
            scores_call = (
                f"_stride_matrix_scores_native(query, targets, matrix_value, {flag}, "
                "gap_open, gap_extend)"
            )
            sql.append(
                create_sql(
                    f"stride_{stem}_matrix_scores",
                    f"query text, targets text[], matrix_value {matrix_type}, "
                    "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL",
                    "bigint[]",
                    scores_call,
                    strict=False,
                )
            )
            path_call = (
                f"_stride_matrix_alignment_path_native(query, target, matrix_value, {flag}, "
                "true, false, gap_open, gap_extend)"
            )
            for suffix in ("matrix_path", "matrix_path_info"):
                sql.append(
                    create_sql(
                        f"stride_{stem}_{suffix}",
                        scalar_args,
                        "jsonb",
                        path_call,
                        strict=False,
                    )
                )
            cigar_call = (
                f"_stride_matrix_alignment_cigar_native(query, target, matrix_value, {flag}, "
                "true, true, gap_open, gap_extend)"
            )
            sql.append(
                create_sql(
                    f"stride_{stem}_matrix_cigar",
                    scalar_args,
                    "text",
                    cigar_call,
                    strict=False,
                )
            )

        for local, suffix in ((True, "local"), (False, "global")):
            flag = "true" if local else "false"
            sql.append(
                create_sql(
                    f"stride_cdist_matrix_{suffix}",
                    f"queries text[], targets text[], matrix_value {matrix_type}, "
                    "gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL",
                    "bigint[]",
                    f"_stride_matrix_cdist_native(queries, targets, matrix_value, {flag}, "
                    "gap_open, gap_extend)",
                    strict=False,
                )
            )

        for is_top_k, suffix in ((False, "above_threshold"), (True, "top_k")):
            parameter_name = "k" if is_top_k else "threshold"
            sql.append(
                create_sql(
                    f"stride_cdist_matrix_{suffix}",
                    f"queries text[], targets text[], matrix_value {matrix_type}, "
                    f"local boolean, {parameter_name} bigint, gap_open bigint DEFAULT NULL, "
                    "gap_extend bigint DEFAULT NULL",
                    "jsonb",
                    f"_stride_matrix_rank_native(queries, targets, matrix_value, local, "
                    f"{parameter_name}, {'true' if is_top_k else 'false'}, gap_open, gap_extend)",
                    strict=False,
                )
            )

    OUTPUT.write_text("\n".join(sql), encoding="utf-8")


if __name__ == "__main__":
    main()
