-- Generated by bindings/postgres/generate_sql.py.

-- stride-align 0.6.0 for PostgreSQL 16, 17, and 18.

CREATE FUNCTION _stride_score_native(query text, target text, scorer text, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint, similarity_cutoff double precision, distance_cutoff bigint) RETURNS double precision
AS 'MODULE_PATHNAME', 'stride_pg_score'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_scores_native(query text, targets text[], scorer text, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint, similarity_cutoff double precision, distance_cutoff bigint) RETURNS double precision[]
AS 'MODULE_PATHNAME', 'stride_pg_scores'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_top_k_native(query text, targets text[], scorer text, k bigint, best boolean, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_top_k'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_cdist_native(queries text[], targets text[], scorer text, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint) RETURNS double precision[]
AS 'MODULE_PATHNAME', 'stride_pg_cdist'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_cdist_above_threshold_native(queries text[], targets text[], scorer text, threshold double precision, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_cdist_above_threshold'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_cdist_top_k_native(queries text[], targets text[], scorer text, k bigint, reject_duplicates boolean, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_cdist_top_k'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_cdist_top_k_per_query_native(queries text[], targets text[], scorer text, k bigint, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint, prefix_weight double precision, prefix_threshold double precision, prefix_cap bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_cdist_top_k_per_query'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_detect_best_backend() RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_backend'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_align_simd_level() RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_backend'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_encoding_info() RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_encoding'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_prepare_info(query text, target text) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_prepare_info'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_available_backends() RETURNS text[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN ARRAY[stride_detect_best_backend()];

CREATE FUNCTION stride_backend_is_available(backend text) RETURNS boolean
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN lower(backend) = lower(stride_detect_best_backend());

CREATE FUNCTION stride_levenshtein(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_levenshtein_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_osa(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_osa_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_true_damerau_levenshtein(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'true_damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_true_damerau_levenshtein_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'true_damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_indel(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_indel_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_hamming(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'hamming', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_hamming_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'hamming_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_levenshtein_score(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_levenshtein_score(query text, target text, score_cutoff bigint) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, score_cutoff)::bigint;

CREATE FUNCTION stride_levenshtein_normalized_score(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_levenshtein_normalized_score(query text, target text, score_cutoff double precision) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, score_cutoff, NULL);

CREATE FUNCTION stride_damerau_levenshtein_score(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_damerau_levenshtein_normalized_score(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_true_damerau_levenshtein_score(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'true_damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_true_damerau_levenshtein_normalized_score(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'true_damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_indel_score(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_indel_score(query text, target text, score_cutoff bigint) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, score_cutoff)::bigint;

CREATE FUNCTION stride_indel_normalized_score(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_indel_normalized_score(query text, target text, score_cutoff double precision) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'indel_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, score_cutoff, NULL);

CREATE FUNCTION stride_hamming_score(query text, target text) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'hamming', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_hamming_normalized_score(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'hamming_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'jaro', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'jaro', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro_winkler(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'jaro_winkler', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro_winkler_similarity(query text, target text, prefix_weight double precision DEFAULT 0.1, prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'jaro_winkler', 2, -1, -1, -1, prefix_weight, prefix_threshold, prefix_cap, NULL, NULL);

CREATE FUNCTION stride_smith_waterman(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman', match_score, mismatch_score, gap_score, gap_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_smith_waterman_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman', match_score, mismatch_score, gap_score, gap_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_smith_waterman_affine(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -2, gap_extend_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_smith_waterman_normalized_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman_normalized', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_smith_waterman_farrar_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_smith_waterman_farrar_normalized_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'smith_waterman_normalized', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_needleman_wunsch(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'needleman_wunsch', match_score, mismatch_score, gap_score, gap_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_needleman_wunsch_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'needleman_wunsch', match_score, mismatch_score, gap_score, gap_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_needleman_wunsch_affine(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -2, gap_extend_score bigint DEFAULT -1) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'needleman_wunsch', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL)::bigint;

CREATE FUNCTION stride_needleman_wunsch_normalized_score(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_score_native(query, target, 'needleman_wunsch_normalized', match_score, mismatch_score, gap_open_score, gap_extend_score, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_levenshtein_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_levenshtein_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_damerau_levenshtein_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_damerau_levenshtein_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_true_damerau_levenshtein_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'true_damerau_levenshtein', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_true_damerau_levenshtein_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'true_damerau_levenshtein_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_indel_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'indel', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_indel_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'indel_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_hamming_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'hamming', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_hamming_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'hamming_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro_similarities(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'jaro', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_jaro_winkler_similarities(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'jaro_winkler', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_smith_waterman_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'smith_waterman', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_smith_waterman_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'smith_waterman_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_smith_waterman_farrar_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'smith_waterman', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_smith_waterman_farrar_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'smith_waterman_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_needleman_wunsch_scores(query text, targets text[]) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'needleman_wunsch', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL)::bigint[];

CREATE FUNCTION stride_needleman_wunsch_normalized_scores(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, 'needleman_wunsch_normalized', 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_scores(query text, targets text[], scorer text) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_scores_native(query, targets, scorer, 2, -1, -1, -1, 0.1, 0.7, 4, NULL, NULL);

CREATE FUNCTION stride_levenshtein_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'levenshtein', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_levenshtein_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'levenshtein', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_levenshtein_normalized_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'levenshtein_normalized', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_levenshtein_normalized_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'levenshtein_normalized', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_damerau_levenshtein_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'damerau_levenshtein', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_damerau_levenshtein_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'damerau_levenshtein', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_damerau_levenshtein_normalized_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'damerau_levenshtein_normalized', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_damerau_levenshtein_normalized_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'damerau_levenshtein_normalized', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_true_damerau_levenshtein_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'true_damerau_levenshtein', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_true_damerau_levenshtein_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'true_damerau_levenshtein', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_true_damerau_levenshtein_normalized_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'true_damerau_levenshtein_normalized', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_true_damerau_levenshtein_normalized_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'true_damerau_levenshtein_normalized', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_indel_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'indel', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_indel_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'indel', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_indel_normalized_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'indel_normalized', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_indel_normalized_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'indel_normalized', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_hamming_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'hamming', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_hamming_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'hamming', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_hamming_normalized_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'hamming_normalized', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_hamming_normalized_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'hamming_normalized', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_jaro_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'jaro', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_jaro_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'jaro', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_jaro_winkler_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'jaro_winkler', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_jaro_winkler_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'jaro_winkler', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_smith_waterman_top_k(query text, targets text[], k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'smith_waterman', k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_smith_waterman_best(query text, targets text[]) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, 'smith_waterman', 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_extract(query text, targets text[], scorer text, k bigint DEFAULT 5) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, scorer, k, false, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_extract_best(query text, targets text[], scorer text) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_top_k_native(query, targets, scorer, 1, true, 2, -1, -1, -1, 0.1, 0.7, 4);

CREATE FUNCTION stride_cdist(queries text[], targets text[], scorer text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1, prefix_weight double precision DEFAULT 0.1, prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_cdist_native(queries, targets, scorer, match_score, mismatch_score, gap_open_score, gap_extend_score, prefix_weight, prefix_threshold, prefix_cap);

CREATE FUNCTION stride_cdist_above_threshold(queries text[], targets text[], scorer text, threshold double precision, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1, prefix_weight double precision DEFAULT 0.1, prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_cdist_above_threshold_native(queries, targets, scorer, threshold, match_score, mismatch_score, gap_open_score, gap_extend_score, prefix_weight, prefix_threshold, prefix_cap);

CREATE FUNCTION stride_cdist_top_k(queries text[], targets text[], scorer text, k bigint, reject_duplicates boolean DEFAULT false, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1, prefix_weight double precision DEFAULT 0.1, prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_cdist_top_k_native(queries, targets, scorer, k, reject_duplicates, match_score, mismatch_score, gap_open_score, gap_extend_score, prefix_weight, prefix_threshold, prefix_cap);

CREATE FUNCTION stride_cdist_top_k_per_query(queries text[], targets text[], scorer text, k bigint DEFAULT 5, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1, prefix_weight double precision DEFAULT 0.1, prefix_threshold double precision DEFAULT 0.7, prefix_cap bigint DEFAULT 4) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_cdist_top_k_per_query_native(queries, targets, scorer, k, match_score, mismatch_score, gap_open_score, gap_extend_score, prefix_weight, prefix_threshold, prefix_cap);

CREATE FUNCTION stride_lcs_length(query text, target text) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_lcs_length'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_lcs_substring_length(query text, target text) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_lcs_substring_length'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_lcs_substring(query text, target text) RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_lcs_substring'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_ngram_native(query text, target text, metric text, n bigint) RETURNS double precision
AS 'MODULE_PATHNAME', 'stride_pg_ngram'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_ngram_scores_native(query text, targets text[], metric text, n bigint) RETURNS double precision[]
AS 'MODULE_PATHNAME', 'stride_pg_ngram_scores'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_similarity_native(query text, target text, metric text) RETURNS double precision
AS 'MODULE_PATHNAME', 'stride_pg_similarity'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_similarity_scores_native(query text, targets text[], metric text) RETURNS double precision[]
AS 'MODULE_PATHNAME', 'stride_pg_similarity_scores'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_jaccard(query text, target text, n bigint DEFAULT 2) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_native(query, target, 'jaccard', n);

CREATE FUNCTION stride_jaccard_similarities(query text, targets text[], n bigint DEFAULT 2) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_scores_native(query, targets, 'jaccard', n);

CREATE FUNCTION stride_dice(query text, target text, n bigint DEFAULT 2) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_native(query, target, 'dice', n);

CREATE FUNCTION stride_dice_similarities(query text, targets text[], n bigint DEFAULT 2) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_scores_native(query, targets, 'dice', n);

CREATE FUNCTION stride_cosine(query text, target text, n bigint DEFAULT 2) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_native(query, target, 'cosine', n);

CREATE FUNCTION stride_cosine_similarities(query text, targets text[], n bigint DEFAULT 2) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_scores_native(query, targets, 'cosine', n);

CREATE FUNCTION stride_overlap(query text, target text, n bigint DEFAULT 2) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_native(query, target, 'overlap', n);

CREATE FUNCTION stride_overlap_similarities(query text, targets text[], n bigint DEFAULT 2) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_ngram_scores_native(query, targets, 'overlap', n);

CREATE FUNCTION stride_ratcliff_obershelp_similarity(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'ratcliff_obershelp');

CREATE FUNCTION stride_ratcliff_obershelp_similarities(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'ratcliff_obershelp');

CREATE FUNCTION stride_partial_ratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'partial_ratio');

CREATE FUNCTION stride_partial_ratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'partial_ratio');

CREATE FUNCTION stride_token_sort_ratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'token_sort_ratio');

CREATE FUNCTION stride_token_sort_ratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'token_sort_ratio');

CREATE FUNCTION stride_token_set_ratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'token_set_ratio');

CREATE FUNCTION stride_token_set_ratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'token_set_ratio');

CREATE FUNCTION stride_partial_token_sort_ratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'partial_token_sort_ratio');

CREATE FUNCTION stride_partial_token_sort_ratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'partial_token_sort_ratio');

CREATE FUNCTION stride_partial_token_set_ratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'partial_token_set_ratio');

CREATE FUNCTION stride_partial_token_set_ratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'partial_token_set_ratio');

CREATE FUNCTION stride_wratio(query text, target text) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_native(query, target, 'wratio');

CREATE FUNCTION stride_wratios(query text, targets text[]) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_similarity_scores_native(query, targets, 'wratio');

CREATE FUNCTION stride_monge_elkan(query text, target text, inner_scorer text DEFAULT 'jaro', "symmetric" boolean DEFAULT false) RETURNS double precision
AS 'MODULE_PATHNAME', 'stride_pg_monge_elkan'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_phonetic_native(algorithm text, input text, first_option bigint, first_flag boolean, second_flag boolean) RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_phonetic'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_phonetic_equal_native(algorithm text, query text, target text, first_option bigint) RETURNS boolean
AS 'MODULE_PATHNAME', 'stride_pg_phonetic_equal'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_soundex(input text) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('soundex', input, 0, true, true);

CREATE FUNCTION stride_nysiis(input text) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('nysiis', input, 0, true, true);

CREATE FUNCTION stride_match_rating_codex(input text) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('match_rating_codex', input, 0, true, true);

CREATE FUNCTION stride_caverphone(input text) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('caverphone', input, 0, true, true);

CREATE FUNCTION stride_cologne_phonetic(input text) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('cologne_phonetic', input, 0, true, true);

CREATE FUNCTION stride_soundex_equal(query text, target text) RETURNS boolean
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_equal_native('soundex', query, target, 0);

CREATE FUNCTION stride_nysiis_equal(query text, target text) RETURNS boolean
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_equal_native('nysiis', query, target, 0);

CREATE FUNCTION stride_match_rating_compare(query text, target text) RETURNS boolean
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_equal_native('match_rating_compare', query, target, 0);

CREATE FUNCTION stride_metaphone(input text, variant bigint DEFAULT 0) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('metaphone', input, variant, true, true);

CREATE FUNCTION stride_metaphone_equal(query text, target text, variant bigint DEFAULT 0) RETURNS boolean
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_equal_native('metaphone', query, target, variant);

CREATE FUNCTION stride_daitch_mokotoff(input text, branching boolean DEFAULT true, folding boolean DEFAULT true) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_phonetic_native('daitch_mokotoff', input, 0, branching, folding);

CREATE FUNCTION stride_double_metaphone(input text, max_length bigint DEFAULT 64, variant bigint DEFAULT 0) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_double_metaphone'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_beider_morse(input text, rule_type bigint DEFAULT 0, concatenate boolean DEFAULT true, max_phonemes bigint DEFAULT 20) RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_beider_morse'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_dtw_native(query anyarray, target anyarray, "window" double precision, distance text, score_cutoff double precision) RETURNS double precision
AS 'MODULE_PATHNAME', 'stride_pg_dtw'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_dtw_distances_native(query anyarray, targets anyarray, "window" double precision, distance text, score_cutoff double precision) RETURNS double precision[]
AS 'MODULE_PATHNAME', 'stride_pg_dtw_distances'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_dtw(query double precision[], target double precision[], "window" double precision DEFAULT NULL, distance text DEFAULT 'l2_squared', score_cutoff double precision DEFAULT NULL) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_dtw_native(query, target, "window", distance, score_cutoff);

CREATE FUNCTION stride_dtw_distances(query double precision[], targets double precision[], "window" double precision DEFAULT NULL, distance text DEFAULT 'l2_squared', score_cutoff double precision DEFAULT NULL) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_dtw_distances_native(query, targets, "window", distance, score_cutoff);

CREATE FUNCTION stride_dtw(query smallint[], target smallint[], "window" double precision DEFAULT NULL, distance text DEFAULT 'l1', score_cutoff double precision DEFAULT NULL) RETURNS double precision
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_dtw_native(query, target, "window", distance, score_cutoff);

CREATE FUNCTION stride_dtw_distances(query smallint[], targets smallint[], "window" double precision DEFAULT NULL, distance text DEFAULT 'l1', score_cutoff double precision DEFAULT NULL) RETURNS double precision[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_dtw_distances_native(query, targets, "window", distance, score_cutoff);

CREATE FUNCTION _stride_alignment_path_native(query text, target text, local boolean, match_score bigint, mismatch_score bigint, gap_open_score bigint, gap_extend_score bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_alignment_path'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_smith_waterman_path(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_alignment_path_native(query, target, true, match_score, mismatch_score, gap_open_score, gap_extend_score);

CREATE FUNCTION stride_smith_waterman_path_info(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_alignment_path_native(query, target, true, match_score, mismatch_score, gap_open_score, gap_extend_score);

CREATE FUNCTION stride_smith_waterman_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, true, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_smith_waterman_trace_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, true, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_smith_waterman_trade_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, true, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_needleman_wunsch_path(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_alignment_path_native(query, target, false, match_score, mismatch_score, gap_open_score, gap_extend_score);

CREATE FUNCTION stride_needleman_wunsch_path_info(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN _stride_alignment_path_native(query, target, false, match_score, mismatch_score, gap_open_score, gap_extend_score);

CREATE FUNCTION stride_needleman_wunsch_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, false, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_needleman_wunsch_trace_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, false, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_needleman_wunsch_trade_cigar(query text, target text, match_score bigint DEFAULT 2, mismatch_score bigint DEFAULT -1, gap_open_score bigint DEFAULT -1, gap_extend_score bigint DEFAULT -1) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE STRICT
RETURN (_stride_alignment_path_native(query, target, false, match_score, mismatch_score, gap_open_score, gap_extend_score))->>'cigar';

CREATE FUNCTION stride_matrix_available() RETURNS text[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_available'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_keyboard_available() RETURNS text[]
AS 'MODULE_PATHNAME', 'stride_pg_keyboard_available'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_identity_matrix(alphabet text, match_score bigint DEFAULT 1, mismatch_score bigint DEFAULT 0, wildcard text DEFAULT '*', name text DEFAULT 'IDENTITY', gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_identity_matrix'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_ascii_matrix(match_score bigint DEFAULT 1, mismatch_score bigint DEFAULT -1, name text DEFAULT 'ASCII', gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_ascii_matrix'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_from_ncbi_text(matrix_text text, name text DEFAULT '<unnamed>', gap_score bigint DEFAULT -4, wildcard text DEFAULT 'X', gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_matrix_from_ncbi_text'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_substitution_matrix(name text, alphabet text, scores smallint[], gap_score bigint DEFAULT -4, wildcard text DEFAULT 'X', gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_substitution_matrix'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_substitution_matrix(name text, alphabet text, scores integer[], gap_score bigint DEFAULT -4, wildcard text DEFAULT 'X', gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_substitution_matrix'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_substitution_matrix(name text, alphabet text, scores bigint[], gap_score bigint DEFAULT -4, wildcard text DEFAULT 'X', gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_substitution_matrix'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_keyboard_from_confusion_counts(counts double precision[], alphabet text DEFAULT NULL, name text DEFAULT 'KEYBOARD', scale double precision DEFAULT 2.0, match_margin bigint DEFAULT 4, floor double precision DEFAULT NULL, wildcard text DEFAULT NULL, gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_keyboard_from_confusion_counts'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_keyboard_from_npy(contents bytea, name text DEFAULT 'KEYBOARD', alphabet text DEFAULT NULL, wildcard text DEFAULT NULL, transpose boolean DEFAULT false, gap_score bigint DEFAULT -1, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_keyboard_from_npy'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_info(matrix_value text) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_info'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_encode(matrix_value text, input text) RETURNS smallint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_encode'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_score_step_limit(matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_matrix_score_step_limit'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_transpose(matrix_value text, name text DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_matrix_transpose'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_substitution_matrix_score(matrix_value text, query text, target text) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_substitution_matrix_score'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_score_native(query text, target text, matrix_value text, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_path_native(query text, target text, matrix_value text, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_cigar_native(query text, target text, matrix_value text, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_scores_native(query text, targets text[], matrix_value text, local boolean, gap_open bigint, gap_extend bigint) RETURNS bigint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_scores'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_cdist_native(queries text[], targets text[], matrix_value text, local boolean, gap_open bigint, gap_extend bigint) RETURNS bigint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_cdist'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_rank_native(queries text[], targets text[], matrix_value text, local boolean, parameter bigint, top_k boolean, gap_open bigint, gap_extend bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_rank'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_smith_waterman_matrix_score(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_score_native(query, target, matrix_value, true, false, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_scores(query text, targets text[], matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_scores_native(query, targets, matrix_value, true, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_path(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, true, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_path_info(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, true, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_cigar(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_cigar_native(query, target, matrix_value, true, true, true, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_score(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_score_native(query, target, matrix_value, false, false, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_scores(query text, targets text[], matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_scores_native(query, targets, matrix_value, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_path(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, false, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_path_info(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, false, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_cigar(query text, target text, matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_cigar_native(query, target, matrix_value, false, true, true, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_local(queries text[], targets text[], matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_cdist_native(queries, targets, matrix_value, true, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_global(queries text[], targets text[], matrix_value text, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_cdist_native(queries, targets, matrix_value, false, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_above_threshold(queries text[], targets text[], matrix_value text, local boolean, threshold bigint, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_rank_native(queries, targets, matrix_value, local, threshold, false, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_top_k(queries text[], targets text[], matrix_value text, local boolean, k bigint, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_rank_native(queries, targets, matrix_value, local, k, true, gap_open, gap_extend);

CREATE FUNCTION stride_matrix_info(matrix_value bytea) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_info'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_encode(matrix_value bytea, input text) RETURNS smallint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_encode'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_score_step_limit(matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_matrix_score_step_limit'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_matrix_transpose(matrix_value bytea, name text DEFAULT NULL) RETURNS bytea
AS 'MODULE_PATHNAME', 'stride_pg_matrix_transpose'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_substitution_matrix_score(matrix_value bytea, query text, target text) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_substitution_matrix_score'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_score_native(query text, target text, matrix_value bytea, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS bigint
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_path_native(query text, target text, matrix_value bytea, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_alignment_cigar_native(query text, target text, matrix_value bytea, local boolean, return_path boolean, cigar_only boolean, gap_open bigint, gap_extend bigint) RETURNS text
AS 'MODULE_PATHNAME', 'stride_pg_matrix_alignment'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_scores_native(query text, targets text[], matrix_value bytea, local boolean, gap_open bigint, gap_extend bigint) RETURNS bigint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_scores'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_cdist_native(queries text[], targets text[], matrix_value bytea, local boolean, gap_open bigint, gap_extend bigint) RETURNS bigint[]
AS 'MODULE_PATHNAME', 'stride_pg_matrix_cdist'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION _stride_matrix_rank_native(queries text[], targets text[], matrix_value bytea, local boolean, parameter bigint, top_k boolean, gap_open bigint, gap_extend bigint) RETURNS jsonb
AS 'MODULE_PATHNAME', 'stride_pg_matrix_rank'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION stride_smith_waterman_matrix_score(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_score_native(query, target, matrix_value, true, false, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_scores(query text, targets text[], matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_scores_native(query, targets, matrix_value, true, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_path(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, true, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_path_info(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, true, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_smith_waterman_matrix_cigar(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_cigar_native(query, target, matrix_value, true, true, true, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_score(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_score_native(query, target, matrix_value, false, false, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_scores(query text, targets text[], matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_scores_native(query, targets, matrix_value, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_path(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, false, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_path_info(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_path_native(query, target, matrix_value, false, true, false, gap_open, gap_extend);

CREATE FUNCTION stride_needleman_wunsch_matrix_cigar(query text, target text, matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS text
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_alignment_cigar_native(query, target, matrix_value, false, true, true, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_local(queries text[], targets text[], matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_cdist_native(queries, targets, matrix_value, true, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_global(queries text[], targets text[], matrix_value bytea, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS bigint[]
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_cdist_native(queries, targets, matrix_value, false, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_above_threshold(queries text[], targets text[], matrix_value bytea, local boolean, threshold bigint, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_rank_native(queries, targets, matrix_value, local, threshold, false, gap_open, gap_extend);

CREATE FUNCTION stride_cdist_matrix_top_k(queries text[], targets text[], matrix_value bytea, local boolean, k bigint, gap_open bigint DEFAULT NULL, gap_extend bigint DEFAULT NULL) RETURNS jsonb
LANGUAGE SQL IMMUTABLE PARALLEL SAFE
RETURN _stride_matrix_rank_native(queries, targets, matrix_value, local, k, true, gap_open, gap_extend);
