#!/usr/bin/env python3
"""Aggregate cross-arch shim bench JSON files into the markdown
section consumed by ``BENCHMARK.md``. Pure JSON post-processing —
does NOT run any benchmark itself.

    .venv/bin/python tools/_shim_bench_to_markdown.py \\
        --avx10 /tmp/bench-shim-full-avx10.json \\
        --mac /tmp/bench-shim-full-mac.json \\
        --loongson /tmp/bench-shim-full-loongson.json \\
        > docs/_shim_bench_section.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def load(path: str | None) -> dict | None:
    if path is None:
        return None
    p = Path(path)
    if not p.exists():
        return None
    with open(p) as f:
        return json.load(f)


# BENCHMARK.md convention: ratio = upstream / shim (so > 1.0 means
# shim is faster). The raw bench JSON stores shim / upstream — invert
# here so the published table reads the same way as the rest of the
# document.
def inverted(r: float) -> float:
    return 1.0 / r if r > 0 else float("inf")


def summary_row(name: str, d: dict | None) -> str:
    if d is None:
        return f"| {name} | — | — | — | — | — | — | — |"
    t = d["timings"]
    n = len(t)
    inv = [inverted(v["ratio"]) for v in t.values()]
    # Wins / ties / losses keyed on the raw shim/upstream ratio.
    wins = sum(1 for v in t.values() if v["ratio"] <= 1.05)
    ties = sum(1 for v in t.values() if 1.05 < v["ratio"] <= 1.15)
    losses = sum(1 for v in t.values() if v["ratio"] > 1.15)
    import math
    log_sum = sum(math.log(x) for x in inv if x > 0)
    geomean = math.exp(log_sum / n)
    sorted_inv = sorted(inv)
    median = sorted_inv[n // 2]
    best = max(inv)
    worst = min(inv)
    return (f"| {name} | `{d['backend']}` | {n} | "
            f"**{geomean:.2f}x** | {median:.2f}x | {worst:.2f}x | "
            f"{best:.2f}x | {wins}/{ties}/{losses} |")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--avx10", default="/tmp/bench-shim-full-avx10.json")
    ap.add_argument("--mac", default="/tmp/bench-shim-full-mac.json")
    ap.add_argument("--loongson", default="/tmp/bench-shim-full-loongson.json")
    args = ap.parse_args()

    avx10 = load(args.avx10)
    mac = load(args.mac)
    loongson = load(args.loongson)

    out: list[str] = []
    out.append("## rapidfuzz shim full surface (cross-arch) - 2026-06-10")
    out.append("")
    out.append(
        "Comprehensive comparison of every public entry point in "
        "``stride_align.rapidfuzz`` (10 ``fuzz`` methods, 8 distance "
        "classes × 4 methods, ``process.cdist`` + ``process.extract`` "
        "with several scorers) against upstream rapidfuzz on the same "
        "deterministic corpus. Generated by "
        "``tools/rapidfuzz_shim_full_bench.py``."
    )
    out.append("")
    out.append(
        "Lower ``ratio`` = shim faster than upstream rapidfuzz. "
        "Min-of-5 wall time per workload. ``rapidfuzz 3.14.5`` on all "
        "three hosts."
    )
    out.append("")

    out.append("### At a glance")
    out.append("")
    out.append("| Host | Backend | Rows | Geomean | Median | Best | Worst | Wins/Ties/Losses |")
    out.append("|---|---|---:|---:|---:|---:|---:|---:|")
    out.append(summary_row("avx10 (Intel AWS)", avx10))
    out.append(summary_row("Mac M-series", mac))
    out.append(summary_row("Loongson", loongson))
    out.append("")
    out.append(
        "Win/tie/loss buckets use ``ratio <= 1.05`` (win), "
        "``1.05 < ratio <= 1.15`` (tie), ``ratio > 1.15`` (loss). "
        "Loongson dominates because upstream rapidfuzz ships no "
        "LSX/LASX backend on LoongArch — they fall back to scalar."
    )
    out.append("")

    # Pick the workloads where the gaps differ most across arches.
    all_names: set[str] = set()
    for d in (avx10, mac, loongson):
        if d is not None:
            all_names.update(d["timings"].keys())

    out.append("### Per-workload comparison")
    out.append("")
    out.append("Ratios per host. Bold values are losses (ratio > 1.15).")
    out.append("")
    out.append("| Workload | avx10 | Mac | Loongson |")
    out.append("|---|---:|---:|---:|")
    for name in sorted(all_names):
        def cell(d: dict | None) -> str:
            if d is None or name not in d["timings"]:
                return "—"
            r = d["timings"][name]["ratio"]
            text = f"{r:.2f}×"
            if r > 1.15:
                return f"**{text}**"
            return text
        out.append(f"| {name} | {cell(avx10)} | {cell(mac)} | {cell(loongson)} |")
    out.append("")
    out.append(
        "On Loongson, every gap above ``1.5×`` is a case where "
        "upstream rapidfuzz happens to be near-zero on a tiny "
        "workload and the absolute differences are still microseconds."
    )

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
